import tkinter
win=tkinter.Tk()
lb1=tkinter.Label(win,text='user')
lb1.pack()
en1=tkinter.Entry(win)
en1.pack()
lb2=tkinter.Label(win,text='password')
lb2.pack()
en2=tkinter.Entry(win)
en2.pack()
btn=tkinter.Button(win,text='Enter')
btn.pack()
